# Generated by Django 2.0.4 on 2018-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('epi_lon', models.CharField(max_length=100)),
                ('epi_lat', models.CharField(max_length=100)),
                ('magnitude', models.CharField(max_length=100)),
                ('excel_data', models.FileField(upload_to='')),
            ],
        ),
    ]
