# Generated by Django 2.0.4 on 2018-04-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_object',
            old_name='excel_data',
            new_name='geojson_public',
        ),
        migrations.RenameField(
            model_name='earthquake_object',
            old_name='epi_lat',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='earthquake_object',
            name='date',
        ),
        migrations.RemoveField(
            model_name='earthquake_object',
            name='epi_lon',
        ),
        migrations.RemoveField(
            model_name='earthquake_object',
            name='magnitude',
        ),
    ]
