# Generated by Django 2.0.4 on 2018-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0003_auto_20180412_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthquake_object',
            name='geojson_public',
        ),
        migrations.AddField(
            model_name='earthquake_object',
            name='url',
            field=models.CharField(default='url0', max_length=200),
        ),
        migrations.AlterField(
            model_name='earthquake_object',
            name='title',
            field=models.CharField(default='title0', max_length=100),
        ),
    ]
