# Generated by Django 2.0.4 on 2018-04-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0004_auto_20180412_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake_object',
            name='epi_lat',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='earthquake_object',
            name='epi_lon',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='earthquake_object',
            name='magnitude',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
