# Generated by Django 2.0.4 on 2018-04-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0005_auto_20180413_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquake_object',
            old_name='url',
            new_name='private_url',
        ),
        migrations.AddField(
            model_name='earthquake_object',
            name='public_url',
            field=models.CharField(default='url0', max_length=200),
        ),
    ]
