# Generated by Django 2.0.4 on 2018-04-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0006_auto_20180413_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake_object',
            name='public_exists',
            field=models.CharField(default='false', max_length=200),
        ),
    ]
