# Generated by Django 2.0.4 on 2018-04-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0008_auto_20180424_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthquake_object',
            name='public_exists',
        ),
    ]
