# Generated by Django 2.0.4 on 2018-04-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_map', '0009_remove_earthquake_object_public_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake_object',
            name='public_exists',
            field=models.BooleanField(default=False),
        ),
    ]
